import {useEffect,useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {ArrowLeft,LogOut,Phone,ReceiptText,UserRound} from 'lucide-react';
import {request} from '../api';

export default function CustomerAccount(){
 const nav=useNavigate();
 const [token,setToken]=useState(localStorage.getItem('customer_token')||'');
 const [customer,setCustomer]=useState<any>(null); const [mode,setMode]=useState<'login'|'register'>('login'); const [msg,setMsg]=useState(''); const [busy,setBusy]=useState(false);
 useEffect(()=>{if(token)request('/api/customer/me',{},token).then(setCustomer).catch(()=>{localStorage.removeItem('customer_token');localStorage.removeItem('customer_profile');setToken('')})},[token]);
 async function submit(e:any){e.preventDefault();setBusy(true);setMsg('');const fd=new FormData(e.currentTarget);try{const body:any={phone:fd.get('phone'),pin:fd.get('pin')};if(mode==='register')body.name=fd.get('name');const r=await request(`/api/customer/${mode}`,{method:'POST',body:JSON.stringify(body)});localStorage.setItem('customer_token',r.token);localStorage.setItem('customer_profile',JSON.stringify(r.customer));setCustomer(r.customer);setToken(r.token);const ret=new URLSearchParams(location.search).get('return');if(ret)nav(ret)}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 function logout(){localStorage.removeItem('customer_token');localStorage.removeItem('customer_profile');setToken('');setCustomer(null)}
 if(token&&customer)return <main className="page narrow customerAccountPage"><Link className="back" to="/"><ArrowLeft/>Home</Link><section className="panel accountProfile"><div className="accountAvatar"><UserRound/></div><div><div className="eyebrow">MAHI EATS ACCOUNT</div><h1>{customer.name}</h1><p><Phone/> {customer.phone}</p></div></section><div className="accountActions"><Link className="accountAction" to="/orders"><ReceiptText/><span><b>My Orders</b><small>Track and view previous orders</small></span></Link><button className="accountAction" onClick={logout}><LogOut/><span><b>Logout</b><small>Sign out from this device</small></span></button></div></main>;
 return <main className="auth customerAuthPage"><form className="panel customerAuthCard" onSubmit={submit}><Link className="back" to="/"><ArrowLeft/>Back to Mahi Eats</Link><div className="brandMark"><span className="brandDot">M</span><b>Mahi Eats</b></div><div className="authSwitch"><button type="button" className={mode==='login'?'active':''} onClick={()=>setMode('login')}>Login</button><button type="button" className={mode==='register'?'active':''} onClick={()=>setMode('register')}>Create account</button></div><h1>{mode==='login'?'Welcome back':'Create your account'}</h1><p>No OTP. Use your mobile number and PIN.</p>{mode==='register'&&<label>Name<input name="name" required minLength={2} placeholder="Your name"/></label>}<label>Mobile number<input name="phone" required inputMode="tel" placeholder="05xxxxxxxx or +971..."/></label><label>PIN<input name="pin" required inputMode="numeric" pattern="[0-9]{4,6}" minLength={4} maxLength={6} type="password" placeholder="4–6 digit PIN"/></label><button disabled={busy}>{busy?'Please wait…':mode==='login'?'Login':'Create account'}</button><small className="authHint">For better security, use a 6-digit PIN.</small>{msg&&<div className="error">{msg}</div>}</form></main>;
}
