import {useEffect,useRef,useState} from 'react';
import {ChefHat,Clock3,RefreshCw} from 'lucide-react';
import {request} from '../api';

export default function Kitchen(){
 const [token,setToken]=useState(localStorage.getItem('kitchen_token')||''); const [shop,setShop]=useState<any>(null); const [orders,setOrders]=useState<any[]>([]); const [msg,setMsg]=useState(''); const previousIds=useRef<Set<number>>(new Set());
 async function load(){if(!token)return;try{const [s,o]=await Promise.all([request('/api/kitchen/me',{},token),request('/api/kitchen/orders',{},token)]);setShop(s);const ids=new Set<number>(o.map((x:any)=>x.id));if(previousIds.current.size&&o.some((x:any)=>!previousIds.current.has(x.id))){try{const ctx=new AudioContext();const osc=ctx.createOscillator();const gain=ctx.createGain();osc.frequency.value=880;gain.gain.value=.12;osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.35)}catch{}}previousIds.current=ids;setOrders(o);setMsg('')}catch(e:any){setMsg(e.message)}}
 useEffect(()=>{load();if(!token)return;const t=setInterval(load,5000);return()=>clearInterval(t)},[token]);
 async function login(e:any){e.preventDefault();const fd=new FormData(e.currentTarget);try{const r=await request('/api/kitchen/login',{method:'POST',body:JSON.stringify({shop_slug:fd.get('shop_slug'),pin:fd.get('pin')})});localStorage.setItem('kitchen_token',r.token);setToken(r.token);setShop(r.shop)}catch(e:any){setMsg(e.message)}}
 async function status(id:number,status:string){try{await request(`/api/kitchen/orders/${id}/status`,{method:'PATCH',body:JSON.stringify({status})},token);load()}catch(e:any){setMsg(e.message)}}
 if(!token)return <main className="auth darkAuth"><form className="panel kitchenLogin" onSubmit={login}><ChefHat size={42}/><h1>Kitchen</h1><p>Mahi Eats merchant kitchen panel</p><input name="shop_slug" placeholder="Shop slug e.g. pizza-house"/><input name="pin" type="password" placeholder="Kitchen PIN"/><button>Open Kitchen</button>{msg&&<div className="error">{msg}</div>}</form></main>;
 return <main className="kitchenPage"><header className="kitchenHeader"><div><div className="eyebrow">KITCHEN</div><h1>{shop?.name}</h1></div><div className="row"><button className="ghost darkGhost" onClick={load}><RefreshCw/></button><button className="ghost darkGhost" onClick={()=>{localStorage.removeItem('kitchen_token');setToken('')}}>Logout</button></div></header><div className="kitchenGrid">{orders.map(o=><article className={`kitchenOrder status-${o.status}`} key={o.id}><div className="row"><div><div className="orderNo">ORDER #{o.id}</div><h2>{o.customer_name}</h2></div><b>AED {Number(o.total).toFixed(2)}</b></div><div className="kitchenTime"><Clock3 size={16}/>{new Date(o.created_at).toLocaleTimeString()}</div><div className="kitchenItems">{o.items.map((i:any)=><div className="row" key={i.name}><b>{i.qty}× {i.name}</b><span>AED {Number(i.line_total).toFixed(2)}</span></div>)}</div><p>{o.delivery_mode==='mahi_eats'?'Mahi Eats rider':'Shop delivery'} · {o.rider?.name||o.merchant_rider_name||'Waiting for rider'}</p><div className="kitchenActions"><button onClick={()=>status(o.id,'accepted')}>Accept</button><button onClick={()=>status(o.id,'preparing')}>Preparing</button><button className="readyBtn" onClick={()=>status(o.id,'ready')}>Ready</button><button className="cancelBtn" onClick={()=>status(o.id,'cancelled')}>Cancel</button></div></article>)}{!orders.length&&<div className="kitchenEmpty"><ChefHat size={50}/><h2>No active orders</h2><p>New orders will appear automatically.</p></div>}</div>{msg&&<div className="toast">{msg}</div>}</main>
}
