import {useEffect,useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import {
 Search,MapPin,Store,Clock3,Bike,ChevronDown,ShoppingBag,Home,ReceiptText,
 Pizza,Coffee,IceCreamBowl,CupSoda,Beef,ShoppingBasket,HeartPulse,Flower2,
 UtensilsCrossed,BadgePercent,Sparkles,Navigation,Languages,ChevronRight,UserRound
} from 'lucide-react';
import {request} from '../api';

type Coords={latitude:number;longitude:number};
type Shop={id:number;name:string;slug:string;category:string;description?:string;logo_url?:string;banner_url?:string;city:string;latitude?:number|null;longitude?:number|null;delivery_fee:number;min_order:number;estimated_minutes:number;is_open:boolean;operating_status?:'open'|'busy'|'closed';delivery_pricing?:{base_fee:number;per_km_fee:number;free_km:number;max_delivery_km:number;area_note?:string}};
type CategoryKey='all'|'pizza'|'burger'|'coffee'|'dessert'|'juice'|'grocery'|'health'|'flowers';

const categories:{key:CategoryKey;label:string;icon:any;match:string[]}[]=[
 {key:'pizza',label:'Pizza',icon:Pizza,match:['pizza','italian']},
 {key:'burger',label:'Burgers',icon:Beef,match:['burger','fast food']},
 {key:'coffee',label:'Coffee',icon:Coffee,match:['coffee','cafe']},
 {key:'dessert',label:'Desserts',icon:IceCreamBowl,match:['dessert','sweet','bakery','ice cream']},
 {key:'juice',label:'Juice',icon:CupSoda,match:['juice','beverage']},
 {key:'grocery',label:'Groceries',icon:ShoppingBasket,match:['grocery','market','supermarket']},
 {key:'health',label:'Health',icon:HeartPulse,match:['health','pharmacy','medicine']},
 {key:'flowers',label:'Flowers',icon:Flower2,match:['flower','gift']},
];
function categoryMatches(shop:Shop,cat:CategoryKey){if(cat==='all')return true;const row=categories.find(c=>c.key===cat);const text=`${shop.category||''} ${shop.description||''} ${shop.name||''}`.toLowerCase();return !!row?.match.some(k=>text.includes(k))}
function km(lat1:number,lon1:number,lat2:number,lon2:number){const r=6371;const p1=lat1*Math.PI/180,p2=lat2*Math.PI/180;const dp=(lat2-lat1)*Math.PI/180,dl=(lon2-lon1)*Math.PI/180;const a=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return r*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a))}

export default function Marketplace(){
 const [q,setQ]=useState(''); const [shops,setShops]=useState<Shop[]>([]); const [err,setErr]=useState('');
 const [category,setCategory]=useState<CategoryKey>('all'); const [freeOnly,setFreeOnly]=useState(false); const [loading,setLoading]=useState(true);
 const [city,setCity]=useState(localStorage.getItem('mahi_city')||'');
 const savedLat=Number(localStorage.getItem('mahi_lat')||''),savedLng=Number(localStorage.getItem('mahi_lng')||'');
 const [coords,setCoords]=useState<Coords|null>(Number.isFinite(savedLat)&&Number.isFinite(savedLng)&&savedLat!==0&&savedLng!==0?{latitude:savedLat,longitude:savedLng}:null);
 const [locating,setLocating]=useState(false); const [locationDenied,setLocationDenied]=useState(false);
 useEffect(()=>{const t=setTimeout(()=>{setErr('');setLoading(true);let path='/api/public/shops';const params=new URLSearchParams();if(q)params.set('q',q);if(city&&!coords)params.set('city',city);if([...params].length)path+=`?${params.toString()}`;request(path).then(setShops).catch(e=>setErr(e.message)).finally(()=>setLoading(false))},220);return()=>clearTimeout(t)},[q,city,coords]);
 useEffect(()=>{if(coords||!navigator.geolocation)return;setLocating(true);navigator.geolocation.getCurrentPosition(p=>{const c={latitude:p.coords.latitude,longitude:p.coords.longitude};setCoords(c);localStorage.setItem('mahi_lat',String(c.latitude));localStorage.setItem('mahi_lng',String(c.longitude));setLocating(false)},()=>{setLocationDenied(true);setLocating(false)},{enableHighAccuracy:true,timeout:10000,maximumAge:60000})},[]);
 const rows=useMemo(()=>shops.map(s=>{const direct=coords&&s.latitude!=null&&s.longitude!=null?km(coords.latitude,coords.longitude,Number(s.latitude),Number(s.longitude)):null;return {...s,_directKm:direct}}),[shops,coords]);
 const visible=useMemo(()=>rows.filter((s:any)=>{if(!categoryMatches(s,category)|| (freeOnly&&Number((s.delivery_pricing?.base_fee??s.delivery_fee)||0)!==0))return false;if(coords&&s._directKm!=null){const max=Number(s.delivery_pricing?.max_delivery_km||0);if(max>0&&s._directKm>max)return false}return true}).sort((a:any,b:any)=>{if(coords){const ad=a._directKm??999999,bd=b._directKm??999999;if(ad!==bd)return ad-bd}return Number(b.is_open)-Number(a.is_open)||a.name.localeCompare(b.name)}),[rows,category,freeOnly,coords]);
 const openCount=visible.filter(s=>s.is_open).length;
 function changeArea(){const next=prompt('Enter your area or city (example: Fujairah). Leave blank to show all shops.',city);if(next===null)return;const value=next.trim();setCity(value);setCoords(null);localStorage.removeItem('mahi_lat');localStorage.removeItem('mahi_lng');if(value)localStorage.setItem('mahi_city',value);else localStorage.removeItem('mahi_city')}
 function useLocation(){if(!navigator.geolocation){changeArea();return}setLocating(true);navigator.geolocation.getCurrentPosition(p=>{const c={latitude:p.coords.latitude,longitude:p.coords.longitude};setCoords(c);setCity('');setLocationDenied(false);localStorage.setItem('mahi_lat',String(c.latitude));localStorage.setItem('mahi_lng',String(c.longitude));localStorage.removeItem('mahi_city');setLocating(false)},()=>{setLocationDenied(true);setLocating(false)},{enableHighAccuracy:true,timeout:10000,maximumAge:30000})}
 return <main className="marketPage">
  <header className="marketTopbar">
   <Link to="/" className="marketBrand"><span className="brandDot">M</span><b>Mahi Eats</b></Link>
   <button className="locationSelect" onClick={coords?useLocation:changeArea}><MapPin/><span><small>Delivering to</small><b>{coords?'Current location':city||'Choose location'}</b></span><ChevronDown/></button>
   <div className="marketTopActions"><button className="iconAction" title="Use current location" onClick={useLocation}><Navigation/></button><Link className="iconAction" to="/orders" title="Orders"><ShoppingBag/></Link><Link className="iconAction" to="/account" title="Account"><UserRound/></Link><button className="iconAction" title="Language"><Languages/></button></div>
  </header>
  {locating&&<div className="locationBanner"><Navigation/> Finding your current location…</div>}
  {locationDenied&&<button className="locationBanner denied" onClick={useLocation}><MapPin/> Allow location to show shops that deliver to you</button>}
  <section className="marketHero"><div className="marketHeroText"><span className="marketKicker"><Sparkles/> Mahi Eats delivery</span><h1>What are you craving?</h1><p>{coords?'Showing shops near your current location.':'Food, groceries and more from shops around you.'}</p></div><div className="marketSearch"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search restaurants, dishes or shops"/></div></section>
  <section className="quickServices" aria-label="Services"><button className={category==='all'?'serviceTile selected':'serviceTile'} onClick={()=>setCategory('all')}><span><UtensilsCrossed/></span><b>Food</b><small>{shops.length} shops</small></button><button className={category==='grocery'?'serviceTile selected':'serviceTile'} onClick={()=>setCategory('grocery')}><span><ShoppingBasket/></span><b>Groceries</b><small>Everyday essentials</small></button><button className={category==='health'?'serviceTile selected':'serviceTile'} onClick={()=>setCategory('health')}><span><HeartPulse/></span><b>Health</b><small>Wellness shops</small></button><button className={category==='flowers'?'serviceTile selected':'serviceTile'} onClick={()=>setCategory('flowers')}><span><Flower2/></span><b>Flowers</b><small>Gifts & more</small></button></section>
  <section className="marketSection"><div className="marketSectionHead"><div><small>DISCOVER</small><h2>What would you like?</h2></div></div><div className="roundCategories"><button className={category==='all'?'roundCat active':'roundCat'} onClick={()=>setCategory('all')}><span><UtensilsCrossed/></span><b>All</b></button>{categories.slice(0,5).map(c=>{const Icon=c.icon;return <button className={category===c.key?'roundCat active':'roundCat'} key={c.key} onClick={()=>setCategory(c.key)}><span><Icon/></span><b>{c.label}</b></button>})}</div></section>
  <section className="promoStrip"><article className="promoCard orange"><div><BadgePercent/><small>MAHI DEALS</small><h3>Offers near you</h3><p>Discover restaurants with great delivery value.</p></div><span className="promoArt">%</span></article><article className="promoCard dark"><div><Bike/><small>FAST DELIVERY</small><h3>Ready when you are</h3><p>See estimated time before you order.</p></div><span className="promoArt">⚡</span></article><article className="promoCard cream"><div><Store/><small>LOCAL FAVOURITES</small><h3>Explore your city</h3><p>Find new restaurants and local shops.</p></div><span className="promoArt">M</span></article></section>
  <section className="marketSection restaurantSection"><div className="marketSectionHead"><div><small>{coords?'NEAR YOUR LOCATION':city?city.toUpperCase():'MAHI EATS'}</small><h2>Restaurants & shops near you</h2></div><span>{loading?'Loading…':`${openCount} open`}</span></div><div className="filterChips"><button className={!freeOnly?'active':''} onClick={()=>setFreeOnly(false)}>All</button><button className={freeOnly?'active':''} onClick={()=>setFreeOnly(v=>!v)}><Bike/> Free delivery</button>{coords&&<button onClick={useLocation}><Navigation/> Refresh location</button>}<button onClick={()=>{setQ('');setCategory('all');setFreeOnly(false)}}>Reset filters</button></div>{err&&<div className="error marketError"><b>Could not load shops.</b><span>{err}</span></div>}
   <div className="restaurantGrid">{visible.map((s:any)=><Link className={`restaurantCard ${!s.is_open?'isClosed':''}`} to={`/shop/${s.slug}`} key={s.id}><div className="restaurantCover">{s.banner_url?<img src={s.banner_url} alt=""/>:s.logo_url?<img className="coverLogo" src={s.logo_url} alt=""/>:<Store/>}<div className="coverShade"/><span className={s.is_open?'openBadge':'closedBadge'}>{s.operating_status==='busy'?'Busy':s.is_open?'Open':'Closed'}</span>{Number((s.delivery_pricing?.base_fee??s.delivery_fee)||0)===0&&<span className="dealBadge"><Bike/> Free delivery</span>}</div><div className="restaurantInfo"><div className="restaurantTitle"><div className="miniLogo">{s.logo_url?<img src={s.logo_url} alt={s.name}/>:<Store/>}</div><div><h3>{s.name}</h3><p>{s.category}</p></div><ChevronRight/></div><div className="restaurantMeta"><span><Clock3/> {s.estimated_minutes}{s.operating_status==='busy'?'+15':''} min</span><span><Bike/> {Number((s.delivery_pricing?.base_fee??s.delivery_fee)||0)===0?'From Free':`From AED ${Number((s.delivery_pricing?.base_fee??s.delivery_fee)||0).toFixed(2)}`}</span>{coords&&s._directKm!=null&&<span><MapPin/> ~{Number(s._directKm).toFixed(1)} km away</span>}</div><small className="restaurantCity"><MapPin/> {s.city}{Number(s.delivery_pricing?.max_delivery_km||0)>0?` · delivers up to ${Number(s.delivery_pricing?.max_delivery_km).toFixed(0)} km`:``}</small></div></Link>)}</div>
   {!loading&&visible.length===0&&!err&&<div className="marketEmpty"><Store/><h3>No shops deliver here yet</h3><p>{coords?'Try refreshing your location or ask Super Admin to set each shop map location and delivery radius.':'Choose another area or use your current location.'}</p><button onClick={useLocation}>Use current location</button></div>}
  </section>
  <nav className="marketBottomNav"><Link className="active" to="/"><Home/><span>Home</span></Link><button onClick={()=>document.querySelector<HTMLInputElement>('.marketSearch input')?.focus()}><Search/><span>Search</span></button><Link to="/orders"><ReceiptText/><span>Orders</span></Link><Link to="/account"><UserRound/><span>Account</span></Link></nav>
 </main>
}
