import {useEffect,useRef,useState} from 'react';
import {Bike,MapPin,Navigation,Phone,RefreshCw,Store} from 'lucide-react';
import {request} from '../api';

export default function Rider(){
 const [token,setToken]=useState(localStorage.getItem('rider_token')||''); const [rider,setRider]=useState<any>(null); const [orders,setOrders]=useState<any[]>([]); const [msg,setMsg]=useState(''); const watchRef=useRef<number|null>(null);
 async function load(){if(!token)return;try{const [r,o]=await Promise.all([request('/api/rider/me',{},token),request('/api/rider/orders',{},token)]);setRider(r);setOrders(o);setMsg('')}catch(e:any){setMsg(e.message)}}
 useEffect(()=>{load();if(!token)return;const t=setInterval(load,6000);return()=>clearInterval(t)},[token]);
 useEffect(()=>()=>{if(watchRef.current!=null&&navigator.geolocation)navigator.geolocation.clearWatch(watchRef.current)},[]);
 async function login(e:any){e.preventDefault();const fd=new FormData(e.currentTarget);try{const r=await request('/api/rider/login',{method:'POST',body:JSON.stringify({email:fd.get('email'),password:fd.get('password')})});localStorage.setItem('rider_token',r.token);setToken(r.token);setRider(r.rider)}catch(e:any){setMsg(e.message)}}
 async function setStatus(body:any){try{const r=await request('/api/rider/status',{method:'PATCH',body:JSON.stringify(body)},token);setRider(r)}catch(e:any){setMsg(e.message)}}
 function startLocation(){if(!navigator.geolocation){setMsg('Location is not supported');return}if(watchRef.current!=null)return;watchRef.current=navigator.geolocation.watchPosition(async p=>{try{await request('/api/rider/location',{method:'POST',body:JSON.stringify({latitude:p.coords.latitude,longitude:p.coords.longitude})},token);setRider((x:any)=>({...x,is_online:true,latitude:p.coords.latitude,longitude:p.coords.longitude}))}catch(e:any){setMsg(e.message)}},()=>setMsg('Please allow location permission'),{enableHighAccuracy:true,maximumAge:5000,timeout:15000});setStatus({is_online:true,is_available:true});setMsg('Live location started')}
 async function action(id:number,status:string){try{await request(`/api/rider/orders/${id}/status`,{method:'PATCH',body:JSON.stringify({status})},token);load()}catch(e:any){setMsg(e.message)}}
 if(!token)return <main className="auth riderAuth"><form className="panel" onSubmit={login}><div className="brandMark"><span className="brandDot">M</span><b>Mahi Eats Rider</b></div><Bike size={42}/><h1>Rider Login</h1><input name="email" placeholder="Email"/><input name="password" type="password" placeholder="Password"/><button>Login</button>{msg&&<div className="error">{msg}</div>}</form></main>;
 return <main className="page riderPage"><div className="row"><div><div className="eyebrow">MAHI EATS RIDER</div><h1>{rider?.name}</h1></div><div className="row"><button className="ghost" onClick={load}><RefreshCw size={16}/></button><button className="ghost" onClick={()=>{localStorage.removeItem('rider_token');setToken('')}}>Logout</button></div></div><div className="riderControl"><div><b className={rider?.is_online?'open':'closed'}>{rider?.is_online?'ONLINE':'OFFLINE'}</b><small>{rider?.is_available?'Available for orders':'Busy / unavailable'}</small></div><div className="row"><button className="locationBtn" onClick={startLocation}><Navigation size={16}/>Start live location</button><button className="small" onClick={()=>setStatus({is_online:!rider?.is_online,is_available:!rider?.is_online})}>{rider?.is_online?'Go offline':'Go online'}</button></div></div>
 <h2>Assigned deliveries</h2>{orders.map(o=><article className="panel riderOrder" key={o.id}><div className="row"><div><div className="orderNo">ORDER #{o.id}</div><h2>{o.shop?.name}</h2></div><b>AED {Number(o.total).toFixed(2)}</b></div><div className="routeBox"><div><Store/><span><b>Pickup</b>{o.shop?.address||o.shop?.name}</span></div><div><MapPin/><span><b>Deliver</b>{o.delivery_address}</span></div></div><p><b>Customer:</b> {o.customer_name} · <a href={`tel:${o.customer_phone}`}><Phone size={14}/>{o.customer_phone}</a></p><p>Kitchen: <b>{o.status}</b> · Rider: <b>{o.rider_status}</b></p><div className="riderActions"><button onClick={()=>action(o.id,'accepted')}>Accept</button><button disabled={o.status!=='ready'} onClick={()=>action(o.id,'picked_up')}>Picked up</button><button onClick={()=>action(o.id,'on_the_way')}>On the way</button><button className="readyBtn" onClick={()=>action(o.id,'delivered')}>Delivered</button></div></article>)}{!orders.length&&<div className="empty panel">No assigned orders right now.</div>}{msg&&<div className="toast">{msg}</div>}</main>
}
