import {useEffect,useState} from 'react';
import {BarChart3,ChefHat,ClipboardList,CreditCard,DollarSign,Settings,Store,Wallet,Tags,Users,MessageSquare,Bell,ShieldCheck,LayoutGrid} from 'lucide-react';
import {request} from '../api';

type Tab='dashboard'|'orders'|'reports'|'menu'|'settings'|'kitchen';
const money=(v:any)=>Number(v||0).toFixed(2);
function fileDataUrl(file:File){return new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||''));r.onerror=()=>reject(new Error('Could not read image'));r.readAsDataURL(file)})}

export default function ShopAdmin(){
 const [token,setToken]=useState(localStorage.getItem('shop_token')||'');
 const [shop,setShop]=useState<any>(null); const [dash,setDash]=useState<any>(null);
 const [cats,setCats]=useState<any[]>([]); const [products,setProducts]=useState<any[]>([]); const [orders,setOrders]=useState<any[]>([]);
 const [report,setReport]=useState<any>(null); const [period,setPeriod]=useState('today');
 const [tab,setTab]=useState<Tab>('dashboard'); const [msg,setMsg]=useState('');

 async function load(){if(!token)return;try{const [s,d,c,p,o]=await Promise.all([request('/api/shop-admin/me',{},token),request('/api/shop-admin/dashboard',{},token),request('/api/shop-admin/categories',{},token),request('/api/shop-admin/products',{},token),request('/api/shop-admin/orders',{},token)]);setShop(s);setDash(d);setCats(c);setProducts(p);setOrders(o);setMsg('')}catch(e:any){setMsg(e.message)}}
 async function loadReport(p=period){if(!token)return;try{setReport(await request(`/api/shop-admin/reports?period=${p}`,{},token))}catch(e:any){setMsg(e.message)}}
 useEffect(()=>{load();if(!token)return;const t=window.setInterval(load,8000);return()=>window.clearInterval(t)},[token]);
 useEffect(()=>{if(tab==='reports')loadReport()},[tab,period]);
 async function login(e:any){e.preventDefault();const fd=new FormData(e.currentTarget);try{const r=await request('/api/shop-admin/login',{method:'POST',body:JSON.stringify({email:fd.get('email'),password:fd.get('password')})});localStorage.setItem('shop_token',r.token);setToken(r.token)}catch(e:any){setMsg(e.message)}}
 async function addCategory(){const name=prompt('Category name');if(!name)return;try{await request('/api/shop-admin/categories',{method:'POST',body:JSON.stringify({name})},token);load()}catch(e:any){setMsg(e.message)}}
 async function addProduct(){const name=prompt('Product name');if(!name)return;const price=Number(prompt('Price AED'));if(!price)return;const cat=Number(prompt(`Category ID (blank = none)\n${cats.map(c=>`${c.id}: ${c.name}`).join('\n')}`)||0)||null;const description=prompt('Description (optional)')||null;const image_url=prompt('Image URL (optional)')||null;try{await request('/api/shop-admin/products',{method:'POST',body:JSON.stringify({name,price,category_id:cat,description,image_url})},token);load()}catch(e:any){setMsg(e.message)}}
 async function cancelOrder(id:number){if(!confirm('Cancel this order?'))return;try{await request(`/api/shop-admin/orders/${id}/status`,{method:'PATCH',body:JSON.stringify({status:'cancelled'})},token);load()}catch(e:any){setMsg(e.message)}}
 async function delivered(id:number){try{await request(`/api/shop-admin/orders/${id}/status`,{method:'PATCH',body:JSON.stringify({status:'delivered'})},token);load()}catch(e:any){setMsg(e.message)}}
 async function merchantRider(o:any){const name=prompt('Shop rider name');if(!name)return;const phone=prompt('Shop rider phone');if(!phone)return;try{await request(`/api/shop-admin/orders/${o.id}/merchant-rider`,{method:'PATCH',body:JSON.stringify({name,phone})},token);load()}catch(e:any){setMsg(e.message)}}
 async function setKitchenPin(){const pin=prompt('Set kitchen PIN (4-12 characters)');if(!pin)return;try{await request('/api/shop-admin/kitchen-pin',{method:'POST',body:JSON.stringify({pin})},token);setMsg(`Kitchen login ready. Shop slug: ${shop.slug}`);load()}catch(e:any){setMsg(e.message)}}
 async function setRestaurantStatus(status:'open'|'busy'|'closed'){try{await request('/api/shop-admin/settings',{method:'PATCH',body:JSON.stringify({operating_status:status})},token);load()}catch(e:any){setMsg(e.message)}}
 async function saveSettings(e:any){e.preventDefault();const fd=new FormData(e.currentTarget);try{let logo_url=String(fd.get('logo_url')||'')||null;let banner_url=String(fd.get('banner_url')||'')||null;const logoFile=fd.get('logo_file') as File|null;const bannerFile=fd.get('banner_file') as File|null;if(logoFile&&logoFile.size){if(logoFile.size>1_500_000)throw new Error('Logo image must be under 1.5 MB');logo_url=await fileDataUrl(logoFile)}if(bannerFile&&bannerFile.size){if(bannerFile.size>2_500_000)throw new Error('Banner image must be under 2.5 MB');banner_url=await fileDataUrl(bannerFile)}const body={min_order:Number(fd.get('min_order')),estimated_minutes:Number(fd.get('estimated_minutes')),address:String(fd.get('address')||''),phone:String(fd.get('phone')||''),description:String(fd.get('description')||''),logo_url,banner_url};await request('/api/shop-admin/settings',{method:'PATCH',body:JSON.stringify(body)},token);setMsg('Settings saved');load()}catch(e:any){setMsg(e.message)}}

 if(!token)return <main className="auth"><form className="panel" onSubmit={login}><div className="brandMark"><span className="brandDot">M</span><b>Mahi Eats</b></div><h1>Shop Admin</h1><p>Login opens only your own shop dashboard.</p><input name="email" placeholder="Email"/><input name="password" type="password" placeholder="Password"/><button>Login</button>{msg&&<div className="error">{msg}</div>}</form></main>;
 const today=dash?.today||{};
 return <main className="page adminPage faiShopAdmin"><div className="adminHero"><div className="shopAdminIdentity">{shop?.logo_url?<img src={shop.logo_url}/>:<div className="adminLogoFallback"><Store/></div>}<div><div className="eyebrow">SHOP ADMIN</div><h1>{shop?.name||'Shop'}</h1><div className="adminMeta">{shop?.category} · {shop?.city} · Commission {Number(shop?.commission_percent||0).toFixed(1)}%</div></div></div><div className="row"><button className="ghost" onClick={load}>↻</button><button className="ghost" onClick={()=>{localStorage.removeItem('shop_token');setToken('')}}>Logout</button></div></div>
 {tab==='dashboard'&&dash&&<><section className="restaurantStatusCard"><div><h2>Restaurant Status</h2><p>Controls whether customers can place an order</p></div><div className="restaurantStatusButtons"><button className={(shop?.operating_status||'open')==='open'?'active openStatus':''} onClick={()=>setRestaurantStatus('open')}>Open</button><button className={shop?.operating_status==='busy'?'active busyStatus':''} onClick={()=>setRestaurantStatus('busy')}>Busy</button><button className={(shop?.operating_status==='closed'||!shop?.is_open)?'active closedStatus':''} onClick={()=>setRestaurantStatus('closed')}>Closed</button></div></section>
 <section className="faiAdminTiles">
  <button onClick={()=>setTab('orders')}><ClipboardList/><span><b>Orders</b><small>Live and past orders</small></span></button>
  <button onClick={()=>setTab('reports')}><BarChart3/><span><b>Sales & Reports</b><small>Revenue, commission and payments</small></span></button>
  <button onClick={()=>setTab('reports')}><Wallet/><span><b>Finance</b><small>Cash/card and shop receivable</small></span></button>
  <button onClick={()=>setTab('menu')}><Store/><span><b>Menu</b><small>Items, prices and categories</small></span></button>
  <button onClick={()=>setTab('menu')}><Tags/><span><b>Offers & Deals</b><small>Menu promotions and combinations</small></span></button>
  <button onClick={()=>setTab('orders')}><Users/><span><b>Customers</b><small>Customer orders and history</small></span></button>
  <button onClick={()=>setTab('orders')}><Bell/><span><b>Notifications</b><small>Order activity and updates</small></span></button>
  <button onClick={()=>setTab('reports')}><MessageSquare/><span><b>Feedback</b><small>Sales and order review area</small></span></button>
  <button onClick={()=>setTab('settings')}><ShieldCheck/><span><b>Admin Controls</b><small>Branding and shop settings</small></span></button>
  <button onClick={()=>setTab('kitchen')}><ChefHat/><span><b>Kitchen Display</b><small>Open kitchen order screen</small></span></button>
 </section>
 <section className="dashboardLead compactDash"><div><small>TODAY CUSTOMER PAYMENTS</small><strong>AED {money(today.customer_sales)}</strong><span>{today.orders||0} orders · {today.pending||0} pending</span></div><div className="dashboardMiniGrid"><div><span>Shop food sale</span><b>AED {money(today.food_sales)}</b></div><div><span>Cash / Card</span><b>{today.cash_orders||0} / {today.card_orders||0}</b></div><div><span>Mahi Eats commission</span><b>AED {money(today.commission)}</b></div><div><span>Shop receivable</span><b>AED {money(today.shop_receivable)}</b></div></div></section></>}
 {tab!=='dashboard'&&<div className="adminSubnav"><button onClick={()=>setTab('dashboard')}><LayoutGrid/> Dashboard</button><span>{tab==='orders'?'Orders':tab==='reports'?'Sales & Reports':tab==='menu'?'Menu':tab==='kitchen'?'Kitchen':'Settings'}</span></div>}
 {tab==='orders'&&<section className="panel"><div className="row"><div><h2>Orders</h2><p className="hint">Accept → Preparing → Ready is controlled only from Kitchen.</p></div><a className="buttonLink secondary" href="/kitchen" target="_blank">Open Kitchen</a></div>{orders.map(o=><div className="order" key={o.id}><div className="row"><b>#{o.id} · {o.customer_name}</b><b>AED {money(o.total)}</b></div><div className="orderBadges"><span className={`statusPill ${o.status}`}>{o.status}</span><span>{o.payment_method}</span><span>{o.delivery_mode==='mahi_eats'?'Mahi Eats delivery':'Shop delivery'}</span></div><p>{o.items.map((i:any)=>`${i.qty}× ${i.name}`).join(', ')}</p><small>{o.customer_phone} · {o.delivery_address}</small>{o.rider&&<p><small>Mahi Eats rider: {o.rider.name} · {o.rider_status}</small></p>}{o.merchant_rider_name&&<p><small>Shop rider: {o.merchant_rider_name} · {o.merchant_rider_phone}</small></p>}<div className="orderAdminActions">{!['cancelled','delivered'].includes(o.status)&&<button className="small dangerSmall" onClick={()=>cancelOrder(o.id)}>Cancel</button>}{o.delivery_mode==='shop'&&!['cancelled','delivered'].includes(o.status)&&<><button className="small" onClick={()=>merchantRider(o)}>{o.merchant_rider_name?'Change rider':'Set rider'}</button>{o.status==='ready'&&<button className="small" onClick={()=>delivered(o.id)}>Mark Delivered</button>}</>}</div></div>)}{!orders.length&&<p>No orders yet.</p>}</section>}

 {tab==='reports'&&<section><div className="row reportHeader"><div><h2>Sales & Reports</h2><p className="hint">Shop sales and commission payable to Mahi Eats.</p></div><select value={period} onChange={e=>setPeriod(e.target.value)}><option value="today">Today</option><option value="week">This Week</option><option value="month">This Month</option><option value="all">All Time</option></select></div>{report&&<><div className="reportStats"><div><Wallet/><span>Customer Sales</span><b>AED {money(report.stats.customer_sales)}</b></div><div><Store/><span>Food Sales</span><b>AED {money(report.stats.food_sales)}</b></div><div><CreditCard/><span>Cash / Card</span><b>AED {money(report.stats.cash_sales)} / {money(report.stats.card_sales)}</b></div><div><DollarSign/><span>Mahi Eats Commission</span><b>AED {money(report.stats.commission)}</b></div><div><BarChart3/><span>Shop Receivable</span><b>AED {money(report.stats.shop_receivable)}</b></div></div><div className="tableWrap"><table><thead><tr><th>Order</th><th>Date</th><th>Status</th><th>Payment</th><th>Total</th></tr></thead><tbody>{report.orders.map((o:any)=><tr key={o.id}><td>#{o.id} · {o.customer_name}</td><td>{new Date(o.created_at).toLocaleString('en-AE',{timeZone:'Asia/Dubai'})}</td><td>{o.status}</td><td>{o.payment_method}</td><td>AED {money(o.total)}</td></tr>)}</tbody></table></div></>}</section>}

 {tab==='menu'&&<section className="panel"><div className="row"><h2>Menu</h2><div><button className="small" onClick={addCategory}>+ Category</button> <button className="small" onClick={addProduct}>+ Product</button></div></div><p><b>Categories:</b> {cats.map(c=>`${c.name} (#${c.id})`).join(', ')||'None'}</p>{products.map(p=><div className="menuAdminRow" key={p.id}>{p.image_url?<img src={p.image_url}/>:<div className="menuImagePlaceholder"><Store/></div>}<span><b>{p.name}</b><small>{p.is_active?'Active':'Hidden'} · Category #{p.category_id||'-'}</small></span><b>AED {money(p.price)}</b></div>)}</section>}

 {tab==='kitchen'&&<section className="panel kitchenAdminCard"><ChefHat size={40}/><h2>Kitchen App</h2><p>Kitchen staff receives new orders here. Only Kitchen can Accept → Preparing → Ready.</p><div className="infoBox"><b>Shop slug</b><code>{shop?.slug}</code><b>Kitchen PIN</b><span>{shop?.kitchen_ready?'Set ✓':'Not set'}</span></div><button onClick={setKitchenPin}>{shop?.kitchen_ready?'Change Kitchen PIN':'Set Kitchen PIN'}</button><p><a className="buttonLink secondary" href="/kitchen" target="_blank">Open Kitchen App</a></p></section>}

 {tab==='settings'&&shop&&<form className="panel settingsGrid" onSubmit={saveSettings}><h2>Shop Settings & Branding</h2><div className="fullLabel infoBox"><b>Delivery settings are controlled by Mahi Eats Super Admin</b><span>{shop.delivery_mode==='mahi_eats'?'Mahi Eats riders':'Shop own delivery'} · Base AED {money(shop.delivery_pricing?.base_fee??shop.delivery_fee)} · up to {Number(shop.delivery_pricing?.max_delivery_km||0).toFixed(1)} km</span></div><label>Logo URL<input name="logo_url" defaultValue={shop.logo_url?.startsWith('data:')?'':shop.logo_url||''} placeholder="https://...logo.png"/></label><label>Upload Logo<input name="logo_file" type="file" accept="image/*"/></label><label>Banner URL<input name="banner_url" defaultValue={shop.banner_url?.startsWith('data:')?'':shop.banner_url||''} placeholder="https://...banner.jpg"/></label><label>Upload Banner<input name="banner_file" type="file" accept="image/*"/></label><label>Phone<input name="phone" defaultValue={shop.phone||''}/></label><label>Minimum order<input name="min_order" type="number" step="0.01" defaultValue={shop.min_order}/></label><label>Estimated minutes<input name="estimated_minutes" type="number" defaultValue={shop.estimated_minutes}/></label><label className="fullLabel">Description<textarea name="description" defaultValue={shop.description||''}/></label><label className="fullLabel">Address<textarea name="address" defaultValue={shop.address||''}/></label><button className="fullButton">Save settings</button></form>}
 {msg&&<div className="toast">{msg}</div>}</main>
}
