import {useEffect,useMemo,useState} from 'react';
import {Link,useNavigate,useParams} from 'react-router-dom';
import {ArrowLeft,Bike,Clock3,MapPin,Minus,Plus,ShoppingBag,UserRound} from 'lucide-react';
import {request} from '../api';

type Product={id:number;category_id:number|null;name:string;description?:string;price:number;image_url?:string};
type Category={id:number;name:string};

type Coords={latitude:number;longitude:number};

export default function ShopPage(){
 const {slug}=useParams(); const nav=useNavigate();
 const [data,setData]=useState<any>(null); const [cart,setCart]=useState<Record<number,number>>({}); const [message,setMessage]=useState('');
 const [showCheckout,setShowCheckout]=useState(false); const [showLogin,setShowLogin]=useState(false); const [authMode,setAuthMode]=useState<'login'|'register'>('login');
 const [form,setForm]=useState({delivery_address:'',payment_method:'cash'}); const [busy,setBusy]=useState(false); const [authBusy,setAuthBusy]=useState(false);
 const savedLat=Number(localStorage.getItem('mahi_lat')||''); const savedLng=Number(localStorage.getItem('mahi_lng')||'');
 const [coords,setCoords]=useState<Coords|null>(Number.isFinite(savedLat)&&Number.isFinite(savedLng)&&savedLat!==0&&savedLng!==0?{latitude:savedLat,longitude:savedLng}:null);
 const [quote,setQuote]=useState<any>(null); const [quoteBusy,setQuoteBusy]=useState(false); const [customerToken,setCustomerToken]=useState(localStorage.getItem('customer_token')||'');
 useEffect(()=>{request(`/api/public/shops/${slug}`).then(setData).catch(e=>setMessage(e.message))},[slug]);
 useEffect(()=>{if(!coords||!slug)return;setQuoteBusy(true);request(`/api/public/shops/${slug}/delivery-quote`,{method:'POST',body:JSON.stringify(coords)}).then(setQuote).catch(e=>{setQuote(null);setMessage(e.message)}).finally(()=>setQuoteBusy(false))},[coords,slug]);
 const products:Product[]=data?.products||[]; const subtotal=useMemo(()=>products.reduce((sum,p)=>sum+(cart[p.id]||0)*p.price,0),[products,cart]);
 const pricing=data?.shop?.delivery_pricing||{}; const dynamicDelivery=Number(pricing.per_km_fee||0)>0||Number(pricing.free_km||0)>0||Number(pricing.max_delivery_km||0)>0;
 const deliveryFee=quote?Number(quote.delivery_fee||0):Number(pricing.base_fee??data?.shop?.delivery_fee??0); const total=subtotal+(subtotal?deliveryFee:0);
 const add=(id:number,d:number)=>setCart(c=>({...c,[id]:Math.max(0,(c[id]||0)+d)}));
 function useLocation(){if(!navigator.geolocation){setMessage('Location is not supported on this device');return}setQuoteBusy(true);navigator.geolocation.getCurrentPosition(p=>{const c={latitude:p.coords.latitude,longitude:p.coords.longitude};setCoords(c);localStorage.setItem('mahi_lat',String(c.latitude));localStorage.setItem('mahi_lng',String(c.longitude));setMessage('Delivery location added')},()=>{setQuoteBusy(false);setMessage('Location permission was not granted')},{enableHighAccuracy:true,timeout:10000})}
 function startCheckout(){if(!customerToken){setShowLogin(true);return}setShowCheckout(true)}
 async function auth(e:any){e.preventDefault();setAuthBusy(true);setMessage('');const fd=new FormData(e.currentTarget);try{const body:any={phone:fd.get('phone'),pin:fd.get('pin')};if(authMode==='register')body.name=fd.get('name');const r=await request(`/api/customer/${authMode}`,{method:'POST',body:JSON.stringify(body)});localStorage.setItem('customer_token',r.token);localStorage.setItem('customer_profile',JSON.stringify(r.customer));setCustomerToken(r.token);setShowLogin(false);setShowCheckout(true)}catch(e:any){setMessage(e.message)}finally{setAuthBusy(false)}}
 async function checkout(e:any){e.preventDefault();const items=Object.entries(cart).filter(([,q])=>Number(q)>0).map(([id,q])=>({product_id:Number(id),qty:Number(q)}));if(!items.length)return;if(!customerToken){setShowCheckout(false);setShowLogin(true);return}if(dynamicDelivery&&!coords){setMessage('Add your current delivery location so Mahi Eats can calculate road distance and delivery fee');return}if(quote&&!quote.deliverable){setMessage(`This shop delivers up to ${Number(quote.max_delivery_km).toFixed(1)} km by road`);return}setBusy(true);try{const r=await request(`/api/public/shops/${slug}/orders`,{method:'POST',body:JSON.stringify({...form,...(coords||{}),items})},customerToken);localStorage.setItem(`track_phone_${r.order_id}`,r.tracking_phone);setCart({});setShowCheckout(false);nav(`/track/${r.order_id}?phone=${encodeURIComponent(r.tracking_phone)}`)}catch(e:any){if(String(e.message).toLowerCase().includes('login')){localStorage.removeItem('customer_token');setCustomerToken('');setShowCheckout(false);setShowLogin(true)}setMessage(e.message)}finally{setBusy(false)}}
 if(!data)return <main className="page"><Link to="/">← Back</Link><p>{message||'Loading...'}</p></main>;
 const cats:Category[]=data.categories;
 const productCard=(p:Product)=><article className="product" key={p.id}>{p.image_url&&<img src={p.image_url} alt={p.name}/>}<div><h3>{p.name}</h3><p>{p.description}</p><b>AED {p.price.toFixed(2)}</b><div className="qty"><button onClick={()=>add(p.id,-1)}><Minus/></button><span>{cart[p.id]||0}</span><button onClick={()=>add(p.id,1)}><Plus/></button></div></div></article>;
 return <main className="page"><div className="row"><Link className="back" to="/"><ArrowLeft size={18}/>All shops</Link><Link className="small buttonLink secondary" to="/account"><UserRound/> Account</Link></div><section className="shopHero">{data.shop.banner_url&&<img className="banner" src={data.shop.banner_url}/>}<div><div className="row"><div><h1>{data.shop.name}</h1><p>{data.shop.description||data.shop.category}</p></div>{data.shop.logo_url&&<img className="heroLogo" src={data.shop.logo_url}/>}</div><div className="meta"><span><MapPin size={14}/>{data.shop.city}</span><span><Bike size={14}/>{dynamicDelivery?`From AED ${Number(pricing.base_fee||0).toFixed(2)} · AED ${Number(pricing.per_km_fee||0).toFixed(2)}/km`:`Delivery AED ${deliveryFee.toFixed(2)}`}</span><span><Clock3 size={14}/>{data.shop.estimated_minutes} min</span>{Number(pricing.max_delivery_km||0)>0&&<span>Up to {Number(pricing.max_delivery_km).toFixed(1)} km</span>}<span className={data.shop.is_open?'open':'closed'}>{data.shop.is_open?'Open':'Closed'}</span></div>{pricing.area_note&&<p className="deliveryAreaNote"><MapPin size={14}/> {pricing.area_note}</p>}</div></section>
 {cats.map(c=><section key={c.id}><h2>{c.name}</h2><div className="productGrid">{products.filter(p=>p.category_id===c.id).map(productCard)}</div></section>)}
 {products.filter(p=>!p.category_id).length>0&&<section><h2>Menu</h2><div className="productGrid">{products.filter(p=>!p.category_id).map(productCard)}</div></section>}
 <div className="cartBar"><span><ShoppingBag/> AED {total.toFixed(2)}</span><button disabled={!subtotal||!data.shop.is_open} onClick={startCheckout}>Checkout</button></div>
 {showLogin&&<div className="modalBack"><form className="panel customerCheckoutLogin" onSubmit={auth}><div className="row"><div><div className="eyebrow">CUSTOMER ACCOUNT</div><h2>{authMode==='login'?'Login to order':'Create Mahi Eats account'}</h2></div><button type="button" className="ghost" onClick={()=>setShowLogin(false)}>Close</button></div><div className="authSwitch"><button type="button" className={authMode==='login'?'active':''} onClick={()=>setAuthMode('login')}>Login</button><button type="button" className={authMode==='register'?'active':''} onClick={()=>setAuthMode('register')}>Create account</button></div>{authMode==='register'&&<label>Name<input name="name" required minLength={2}/></label>}<label>Mobile number<input name="phone" required inputMode="tel" placeholder="05xxxxxxxx"/></label><label>PIN<input name="pin" required inputMode="numeric" pattern="[0-9]{4,6}" type="password" placeholder="4–6 digit PIN"/></label><button disabled={authBusy}>{authBusy?'Please wait…':authMode==='login'?'Login & continue':'Create account & continue'}</button><small className="authHint">No OTP is required.</small></form></div>}
 {showCheckout&&<div className="modalBack"><form className="panel checkoutModal" onSubmit={checkout}><div className="row"><h2>Checkout</h2><button type="button" className="ghost" onClick={()=>setShowCheckout(false)}>Close</button></div><label>Delivery address<textarea required value={form.delivery_address} onChange={e=>setForm({...form,delivery_address:e.target.value})} placeholder="Building, street, area, flat/villa number"/></label><button type="button" className="locationBtn" onClick={useLocation}><MapPin size={16}/>{quoteBusy?'Calculating…':coords?'Update delivery location':'Add current delivery location'}</button>{dynamicDelivery&&<div className={`deliveryQuote ${quote&&!quote.deliverable?'notDeliverable':''}`}>{!coords?<><b>Location required</b><span>Road distance determines this shop's delivery fee.</span></>:quote?<><div className="row"><b>{quote.is_road_distance?'Road distance':'Estimated distance'}</b><strong>{Number(quote.distance_km).toFixed(2)} km</strong></div><div className="row"><span>Delivery fee</span><b>AED {Number(quote.delivery_fee).toFixed(2)}</b></div>{!quote.is_road_distance&&<small>Road routing is not configured yet; Super Admin must add the Google Routes API key.</small>}{!quote.deliverable&&<strong>Outside this shop's {Number(quote.max_delivery_km).toFixed(1)} km delivery limit.</strong>}</>:<span>Calculating delivery distance…</span>}</div>}<div className="bill"><div className="row"><span>Food</span><b>AED {subtotal.toFixed(2)}</b></div><div className="row"><span>Delivery</span><b>AED {deliveryFee.toFixed(2)}</b></div><div className="row totalLine"><span>Total</span><b>AED {total.toFixed(2)}</b></div></div><button disabled={busy||quoteBusy||(dynamicDelivery&&!quote?.deliverable)}>{busy?'Placing order...':'Place cash order'}</button></form></div>}
 {message&&<div className="toast">{message}</div>}
 </main>;
}
