import {useEffect,useState} from 'react';
import {ChefHat,ClipboardList,Settings,Store} from 'lucide-react';
import {request} from '../api';

export default function ShopAdmin(){
 const [token,setToken]=useState(localStorage.getItem('shop_token')||''); const [shop,setShop]=useState<any>(null); const [cats,setCats]=useState<any[]>([]); const [products,setProducts]=useState<any[]>([]); const [orders,setOrders]=useState<any[]>([]); const [stats,setStats]=useState<any>(null); const [tab,setTab]=useState<'orders'|'menu'|'settings'>('orders'); const [msg,setMsg]=useState('');
 async function load(){if(!token)return;try{const [s,c,p,o,st]=await Promise.all([request('/api/shop-admin/me',{},token),request('/api/shop-admin/categories',{},token),request('/api/shop-admin/products',{},token),request('/api/shop-admin/orders',{},token),request('/api/shop-admin/stats',{},token)]);setShop(s);setCats(c);setProducts(p);setOrders(o);setStats(st)}catch(e:any){setMsg(e.message)}}
 useEffect(()=>{load();if(!token)return;const t=setInterval(load,8000);return()=>clearInterval(t)},[token]);
 async function login(e:any){e.preventDefault();const fd=new FormData(e.currentTarget);try{const r=await request('/api/shop-admin/login',{method:'POST',body:JSON.stringify({email:fd.get('email'),password:fd.get('password')})});localStorage.setItem('shop_token',r.token);setToken(r.token)}catch(e:any){setMsg(e.message)}}
 async function addCategory(){const name=prompt('Category name');if(!name)return;try{await request('/api/shop-admin/categories',{method:'POST',body:JSON.stringify({name})},token);load()}catch(e:any){setMsg(e.message)}}
 async function addProduct(){const name=prompt('Product name');if(!name)return;const price=Number(prompt('Price AED'));if(!price)return;const cat=Number(prompt(`Category ID (blank = none)\n${cats.map(c=>`${c.id}: ${c.name}`).join('\n')}`)||0)||null;const description=prompt('Description (optional)')||null;const image_url=prompt('Image URL (optional)')||null;try{await request('/api/shop-admin/products',{method:'POST',body:JSON.stringify({name,price,category_id:cat,description,image_url})},token);load()}catch(e:any){setMsg(e.message)}}
 async function status(id:number,status:string){try{await request(`/api/shop-admin/orders/${id}/status`,{method:'PATCH',body:JSON.stringify({status})},token);load()}catch(e:any){setMsg(e.message)}}
 async function merchantRider(o:any){const name=prompt('Shop rider name');if(!name)return;const phone=prompt('Shop rider phone');if(!phone)return;try{await request(`/api/shop-admin/orders/${o.id}/merchant-rider`,{method:'PATCH',body:JSON.stringify({name,phone})},token);load()}catch(e:any){setMsg(e.message)}}
 async function setKitchenPin(){const pin=prompt('Set kitchen PIN (4-12 digits/characters)');if(!pin)return;try{await request('/api/shop-admin/kitchen-pin',{method:'POST',body:JSON.stringify({pin})},token);setMsg(`Kitchen login ready. Shop slug: ${shop.slug}`);load()}catch(e:any){setMsg(e.message)}}
 async function saveSettings(e:any){e.preventDefault();const fd=new FormData(e.currentTarget);const body={is_open:fd.get('is_open')==='on',delivery_mode:String(fd.get('delivery_mode')),delivery_fee:Number(fd.get('delivery_fee')),min_order:Number(fd.get('min_order')),estimated_minutes:Number(fd.get('estimated_minutes')),address:String(fd.get('address')||''),latitude:fd.get('latitude')?Number(fd.get('latitude')):null,longitude:fd.get('longitude')?Number(fd.get('longitude')):null};try{await request('/api/shop-admin/settings',{method:'PATCH',body:JSON.stringify(body)},token);setMsg('Settings saved');load()}catch(e:any){setMsg(e.message)}}
 if(!token)return <main className="auth"><form className="panel" onSubmit={login}><div className="brandMark"><span className="brandDot">M</span><b>Mahi Eats</b></div><h1>Shop Admin</h1><p>Each shop sees only its own menu, orders and sales.</p><input name="email" placeholder="Email"/><input name="password" type="password" placeholder="Password"/><button>Login</button>{msg&&<div className="error">{msg}</div>}</form></main>;
 return <main className="page"><div className="row"><div><div className="eyebrow">SHOP ADMIN</div><h1>{shop?.name||'Shop'}</h1></div><button className="ghost" onClick={()=>{localStorage.removeItem('shop_token');setToken('')}}>Logout</button></div>
 {stats&&<div className="stats"><div><b>{stats.products}</b><span>Products</span></div><div><b>{stats.orders}</b><span>Orders</span></div><div><b>{stats.pending}</b><span>Pending</span></div><div><b>AED {Number(stats.sales).toFixed(2)}</b><span>Sales</span></div></div>}
 <div className="tabs"><button className={tab==='orders'?'active':''} onClick={()=>setTab('orders')}><ClipboardList/> Orders</button><button className={tab==='menu'?'active':''} onClick={()=>setTab('menu')}><Store/> Menu</button><button className={tab==='settings'?'active':''} onClick={()=>setTab('settings')}><Settings/> Settings</button></div>
 {tab==='orders'&&<section className="panel"><h2>Orders</h2>{orders.map(o=><div className="order" key={o.id}><div className="row"><b>#{o.id} · {o.customer_name}</b><b>AED {Number(o.total).toFixed(2)}</b></div><small>{o.status} · {o.customer_phone} · {o.delivery_mode==='mahi_eats'?'Mahi Eats delivery':'Shop delivery'}</small><p>{o.items.map((i:any)=>`${i.qty}× ${i.name}`).join(', ')}</p><p>{o.delivery_address}</p><div>{['accepted','preparing','ready','cancelled'].map(s=><button className="small" key={s} onClick={()=>status(o.id,s)}>{s}</button>)}{o.delivery_mode==='shop'&&o.status!=='delivered'&&<button className="small" onClick={()=>status(o.id,'delivered')}>delivered</button>}{o.delivery_mode==='shop'&&o.status!=='cancelled'&&<button className="small" onClick={()=>merchantRider(o)}>{o.merchant_rider_name?'Change shop rider':'Set shop rider'}</button>}</div>{o.rider&&<small>Mahi Eats rider: {o.rider.name} · {o.rider_status}</small>}{o.merchant_rider_name&&<small>Shop rider: {o.merchant_rider_name} · {o.merchant_rider_phone}</small>}</div>)}{!orders.length&&<p>No orders yet.</p>}</section>}
 {tab==='menu'&&<section className="panel"><div className="row"><h2>Menu</h2><div><button className="small" onClick={addCategory}>+ Category</button> <button className="small" onClick={addProduct}>+ Product</button></div></div><p><b>Categories:</b> {cats.map(c=>`${c.name} (#${c.id})`).join(', ')||'None'}</p>{products.map(p=><div className="listRow" key={p.id}><span>{p.name}<small>{p.is_active?'Active':'Hidden'}</small></span><b>AED {Number(p.price).toFixed(2)}</b></div>)}</section>}
 {tab==='settings'&&shop&&<div className="adminCols"><form className="panel" onSubmit={saveSettings}><h2>Shop & delivery</h2><label className="checkLine"><input name="is_open" type="checkbox" defaultChecked={shop.is_open}/> Shop open</label><label>Delivery mode<select name="delivery_mode" defaultValue={shop.delivery_mode}><option value="mahi_eats">Mahi Eats riders</option><option value="shop">Shop own delivery</option></select></label><label>Delivery fee<input name="delivery_fee" type="number" step="0.01" defaultValue={shop.delivery_fee}/></label><label>Minimum order<input name="min_order" type="number" step="0.01" defaultValue={shop.min_order}/></label><label>Estimated minutes<input name="estimated_minutes" type="number" defaultValue={shop.estimated_minutes}/></label><label>Address<textarea name="address" defaultValue={shop.address||''}/></label><label>Shop latitude<input name="latitude" type="number" step="any" defaultValue={shop.latitude??''}/></label><label>Shop longitude<input name="longitude" type="number" step="any" defaultValue={shop.longitude??''}/></label><button>Save settings</button></form><div className="panel"><h2><ChefHat/> Kitchen</h2><p>Kitchen is separate for this shop. Staff logs in with shop slug + PIN.</p><div className="infoBox"><b>Shop slug</b><code>{shop.slug}</code><b>Kitchen PIN</b><span>{shop.kitchen_ready?'Set ✓':'Not set'}</span></div><button onClick={setKitchenPin}>{shop.kitchen_ready?'Change Kitchen PIN':'Set Kitchen PIN'}</button><p><a className="buttonLink secondary" href="/kitchen">Open Kitchen panel</a></p></div></div>}
 {msg&&<div className="toast">{msg}</div>}</main>
}
