import {useEffect,useState} from 'react';
import {Bike,Building2,ClipboardList,Plus,RefreshCw} from 'lucide-react';
import {request} from '../api';

const emptyShop={name:'',slug:'',category:'Restaurant',city:'Fujairah',delivery_fee:0,min_order:0,estimated_minutes:30,delivery_mode:'mahi_eats',commission_percent:0,is_active:true,is_open:true};
const emptyRider={name:'',email:'',phone:'',password:''};

export default function SuperAdmin(){
 const [token,setToken]=useState(localStorage.getItem('super_token')||''); const [shops,setShops]=useState<any[]>([]); const [riders,setRiders]=useState<any[]>([]); const [orders,setOrders]=useState<any[]>([]); const [stats,setStats]=useState<any>(null); const [tab,setTab]=useState<'shops'|'riders'|'orders'>('shops'); const [form,setForm]=useState<any>(emptyShop); const [riderForm,setRiderForm]=useState<any>(emptyRider); const [msg,setMsg]=useState('');
 async function load(){if(!token)return;try{const [s,st,r,o]=await Promise.all([request('/api/super/shops',{},token),request('/api/super/stats',{},token),request('/api/super/riders',{},token),request('/api/super/orders',{},token)]);setShops(s);setStats(st);setRiders(r);setOrders(o)}catch(e:any){setMsg(e.message)}}
 useEffect(()=>{load();if(!token)return;const t=setInterval(load,10000);return()=>clearInterval(t)},[token]);
 async function login(e:any){e.preventDefault();const fd=new FormData(e.currentTarget);try{const r=await request('/api/super/login',{method:'POST',body:JSON.stringify({email:fd.get('email'),password:fd.get('password')})});localStorage.setItem('super_token',r.token);setToken(r.token)}catch(e:any){setMsg(e.message)}}
 async function addShop(e:any){e.preventDefault();try{await request('/api/super/shops',{method:'POST',body:JSON.stringify(form)},token);setForm(emptyShop);setMsg('Shop added');load()}catch(e:any){setMsg(e.message)}}
 async function toggle(s:any,key:'is_active'|'is_open'){await request(`/api/super/shops/${s.id}`,{method:'PATCH',body:JSON.stringify({[key]:!s[key]})},token);load()}
 async function addAdmin(s:any){const email=prompt(`Admin email for ${s.name}`);if(!email)return;const password=prompt('Admin password (minimum 6 characters)');if(!password)return;try{await request(`/api/super/shops/${s.id}/admins`,{method:'POST',body:JSON.stringify({name:'Shop Admin',email,password})},token);setMsg('Shop admin created')}catch(e:any){setMsg(e.message)}}
 async function addRider(e:any){e.preventDefault();try{await request('/api/super/riders',{method:'POST',body:JSON.stringify(riderForm)},token);setRiderForm(emptyRider);setMsg('Mahi Eats rider created');load()}catch(e:any){setMsg(e.message)}}
 async function toggleRider(r:any){await request(`/api/super/riders/${r.id}`,{method:'PATCH',body:JSON.stringify({is_active:!r.is_active})},token);load()}
 async function assign(order:any){const available=riders.filter(r=>r.is_active);if(!available.length){setMsg('Create a rider first');return}const text=available.map(r=>`${r.id}: ${r.name} ${r.is_online?'(online)':'(offline)'}`).join('\n');const id=Number(prompt(`Enter rider ID:\n${text}`));if(!id)return;try{await request(`/api/super/orders/${order.id}/assign`,{method:'POST',body:JSON.stringify({rider_id:id})},token);setMsg('Rider assigned');load()}catch(e:any){setMsg(e.message)}}
 if(!token)return <main className="auth"><form className="panel" onSubmit={login}><div className="brandMark"><span className="brandDot">M</span><b>Mahi Eats</b></div><h1>Super Admin</h1><p>Platform owner login</p><input name="email" placeholder="Email"/><input name="password" type="password" placeholder="Password"/><button>Login</button>{msg&&<div className="error">{msg}</div>}</form></main>;
 return <main className="page"><div className="row"><div><div className="eyebrow">MAHI EATS PLATFORM</div><h1>Super Admin</h1></div><div className="row"><button className="ghost" onClick={load}><RefreshCw size={16}/></button><button className="ghost" onClick={()=>{localStorage.removeItem('super_token');setToken('')}}>Logout</button></div></div>
 {stats&&<div className="stats"><div><b>{stats.shops}</b><span>Shops</span></div><div><b>{stats.active_shops}</b><span>Active shops</span></div><div><b>{stats.online_riders}/{stats.riders}</b><span>Online riders</span></div><div><b>{stats.orders}</b><span>Orders</span></div><div><b>AED {Number(stats.sales).toFixed(2)}</b><span>Customer sales</span></div><div><b>AED {Number(stats.commission).toFixed(2)}</b><span>Platform commission</span></div></div>}
 <div className="tabs"><button className={tab==='shops'?'active':''} onClick={()=>setTab('shops')}><Building2/> Shops</button><button className={tab==='riders'?'active':''} onClick={()=>setTab('riders')}><Bike/> Riders</button><button className={tab==='orders'?'active':''} onClick={()=>setTab('orders')}><ClipboardList/> Orders</button></div>
 {tab==='shops'&&<><form className="panel formGrid" onSubmit={addShop}><h2><Plus size={20}/> Add shop</h2><input required placeholder="Shop name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input required placeholder="slug-example" value={form.slug} onChange={e=>setForm({...form,slug:e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,'-')})}/><input placeholder="Category" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/><input placeholder="City" value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/><input type="number" step="0.01" placeholder="Delivery fee" value={form.delivery_fee} onChange={e=>setForm({...form,delivery_fee:Number(e.target.value)})}/><input type="number" step="0.01" placeholder="Minimum order" value={form.min_order} onChange={e=>setForm({...form,min_order:Number(e.target.value)})}/><input type="number" placeholder="Estimated minutes" value={form.estimated_minutes} onChange={e=>setForm({...form,estimated_minutes:Number(e.target.value)})}/><input type="number" step="0.1" placeholder="Commission %" value={form.commission_percent} onChange={e=>setForm({...form,commission_percent:Number(e.target.value)})}/><select value={form.delivery_mode} onChange={e=>setForm({...form,delivery_mode:e.target.value})}><option value="mahi_eats">Mahi Eats riders</option><option value="shop">Shop own delivery</option></select><button>Add Shop</button></form><section><h2>All shops</h2><div className="tableWrap"><table><thead><tr><th>Shop</th><th>Delivery</th><th>Status</th><th>Open</th><th>Actions</th></tr></thead><tbody>{shops.map(s=><tr key={s.id}><td><b>{s.name}</b><br/><small>{s.category} · {s.city} · /{s.slug}</small></td><td>{s.delivery_mode==='mahi_eats'?'Mahi Eats':'Shop own'}</td><td>{s.is_active?'Active':'Suspended'}</td><td>{s.is_open?'Open':'Closed'}</td><td><button className="small" onClick={()=>toggle(s,'is_active')}>{s.is_active?'Suspend':'Activate'}</button> <button className="small" onClick={()=>toggle(s,'is_open')}>{s.is_open?'Close':'Open'}</button> <button className="small" onClick={()=>addAdmin(s)}>Create Admin</button></td></tr>)}</tbody></table></div></section></>}
 {tab==='riders'&&<><form className="panel formGrid" onSubmit={addRider}><h2><Bike size={20}/> Add Mahi Eats rider</h2><input required placeholder="Rider name" value={riderForm.name} onChange={e=>setRiderForm({...riderForm,name:e.target.value})}/><input required placeholder="Email" value={riderForm.email} onChange={e=>setRiderForm({...riderForm,email:e.target.value})}/><input required placeholder="Phone" value={riderForm.phone} onChange={e=>setRiderForm({...riderForm,phone:e.target.value})}/><input required type="password" placeholder="Password" value={riderForm.password} onChange={e=>setRiderForm({...riderForm,password:e.target.value})}/><button>Create Rider</button></form><div className="shopGrid">{riders.map(r=><div className="panel" key={r.id}><div className="row"><h3>{r.name}</h3><span className={r.is_online?'open':'closed'}>{r.is_online?'Online':'Offline'}</span></div><p>{r.phone}<br/>{r.email}</p><p>{r.is_available?'Available':'Busy'} {r.latitude!=null&&`· ${Number(r.latitude).toFixed(4)}, ${Number(r.longitude).toFixed(4)}`}</p><button className="small" onClick={()=>toggleRider(r)}>{r.is_active?'Disable':'Enable'}</button></div>)}</div></>}
 {tab==='orders'&&<section><h2>Platform orders</h2>{orders.map(o=><div className="order" key={o.id}><div className="row"><b>#{o.id} · {o.shop?.name}</b><b>AED {Number(o.total).toFixed(2)}</b></div><small>{o.status} · delivery: {o.delivery_mode==='mahi_eats'?'Mahi Eats':'Shop'} · rider: {o.rider?.name||o.merchant_rider_name||'Not assigned'}</small><p>{o.customer_name} · {o.customer_phone}<br/>{o.delivery_address}</p>{o.delivery_mode==='mahi_eats'&&o.status!=='delivered'&&o.status!=='cancelled'&&<button className="small" onClick={()=>assign(o)}>{o.rider?'Reassign rider':'Assign rider'}</button>}</div>)}</section>}
 {msg&&<div className="toast">{msg}</div>}</main>
}
